web-slate/TwixtUI

react/src/Badges.js, react/src/Divider.js, react/src/Link.js, react/src/NoResult.js, react/src/Popover.js, react/src/Split.js, react/src/Toast.js, react/src/Tooltip.js, react/src/UserFacePile.js
=> added link component

react/src/UserCard.js
=> tech(fix): image size inside a card view

react/src/MultiSelectMenu.js, react/src/OneSelectDropdown.js
=> added mono select drop down

react-examples/stories/Alert.stories.js, react/package-lock.json, react/package.json, react/src/Alert.js, react/src/SimpleTable.js
=> Alert Components

.github/PULL_REQUEST_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE/react-component-docs.md, .github/PULL_REQUEST_TEMPLATE/react-component-fix.md, .github/PULL_REQUEST_TEMPLATE/react-new-component.md
=> add base github PR Template

react-examples/stories/Badges.stories.js, react-examples/stories/Button.stories.js, react-examples/stories/Comments.stories.js, react-examples/stories/Header.stories.js, react-examples/stories/OneSelectDropdown.stories.js, react-examples/stories/SimpleTable.stories.js, react-examples/stories/Switch.stories.js, react-examples/stories/UseFacepile.stories.js, react-examples/stories/UserNameInput.stories.js, react-examples/stories/UserStackList.stories.js, react/package-lock.json, react/src/Badges.js, react/src/UserNameInput.js, react/src/index.js
=> storybook updated

react/src/index.js
Unable to call out the components such as popover,dropdown,copylink
So,Exported the components in index file
=> export components in index file

react/dist/index.js
Some of the components are unable to been called out in react app
Added index files in dist folder for some of the components
=> Index Files in dist folder has been changed

react/src/Switch.js
Switch Component enhancement
Added value and checked props
=> Added value to the switch component

react/src/UserCard.js
=> Passed children props

.gitignore, react/src/CallsToAction/Button/Button.js, react/src/CallsToAction/Button/index.js, react/src/CallsToAction/ButtonGroup/ButtonGroup.js, react/src/CallsToAction/ButtonGroup/index.js, react/src/CallsToAction/FloatingButton/FloatingButton.js, react/src/CallsToAction/FloatingButton/index.js, react/src/CallsToAction/Link/Link.js, react/src/CallsToAction/Link/index.js, react/src/CallsToAction/SplitButton/SplitButton.js, react/src/CallsToAction/SplitButton/index.js, react/src/CallsToAction/ToggleButton/ToggleButton.js, react/src/CallsToAction/ToggleButton/index.js
None
Created CTA empty components
None
=> CTA components structure

react/src/Navigation/Breadcrumb/Breadcrumb.js, react/src/Navigation/Breadcrumb/index.js, react/src/Navigation/Carousel/Carousel.js, react/src/Navigation/Carousel/index.js, react/src/Navigation/DropdownMenu/DropdownMenu.js, react/src/Navigation/DropdownMenu/index.js, react/src/Navigation/MainNavigation/MainNavigation.js, react/src/Navigation/MainNavigation/index.js, react/src/Navigation/Pagination/Pagination.js, react/src/Navigation/Pagination/index.js, react/src/Navigation/Stepper/Stepper.js, react/src/Navigation/Stepper/index.js, react/src/Navigation/Tabs/Tabs.js, react/src/Navigation/Tabs/index.js
Current Problem
None
After Implementation
Navigation empty component added
Steps to Reproduce this issue
None
=> Navigation component structure

react/src/CallsToAction/Button/Button.js, react/src/index.js
Button is ungrouped
Button grouped under CTA
None
=> feat(call-to-action): add button component

react/src/Visualization/AreaChart/AreaChart.js, react/src/Visualization/AreaChart/index.js, react/src/Visualization/BarChart/BarChart.js, react/src/Visualization/BarChart/index.js, react/src/Visualization/LineChart/LineChart.js, react/src/Visualization/LineChart/index.js, react/src/Visualization/SegmentedBarChart/SegmentedBarChart.js, react/src/Visualization/SegmentedBarChart/index.js, react/src/Visualization/Sparkline/Sparkline.js, react/src/Visualization/Sparkline/index.js, react/src/Visualization/StatsTile/StatsTile.js, react/src/Visualization/StatsTile/index.js, react/src/Visualization/Table/Table.js, react/src/Visualization/Table/index.js
No Issues
Created Virtualization Skeleton Component
None
=> Virtualization Skeleton Component

react-examples/stories/Button.jsx, react-examples/stories/Button.stories.js
- Additional Props like background, color, disavled. left icon. spinner, right icon
=> tech(cta/buttons): add component docs with variations

react/src/List/CollapsibleList/CollapsibleList.js, react/src/List/CollapsibleList/index.js, react/src/List/DescriptionList/DescriptionList.js, react/src/List/DescriptionList/index.js, react/src/List/List/List.js, react/src/List/List/index.js, react/src/List/ReorderableList/ReorderableList.js, react/src/List/ReorderableList/index.js, react/src/List/TreeList/TreeList.js, react/src/List/TreeList/index.js
None
List skeleton component
None
=> List skeleton component

react/src/Communications/Badge/Badge.js, react/src/Communications/Badge/index.js, react/src/Communications/Banner/Banner.js, react/src/Communications/Banner/index.js, react/src/Communications/HelpMessage/HelpMessage.js, react/src/Communications/HelpMessage/index.js, react/src/Communications/HoverCard/HoverCard.js, react/src/Communications/HoverCard/index.js, react/src/Communications/Media/Media.js, react/src/Communications/Media/index.js, react/src/Communications/NoDataBlock/NoDataBlock.js, react/src/Communications/NoDataBlock/index.js, react/src/Communications/Notice/Notice.js, react/src/Communications/Notice/index.js, react/src/Communications/ProfilePic/ProfilePic.js, react/src/Communications/ProfilePic/index.js, react/src/Communications/StatusDot/StatusDot.js, react/src/Communications/StatusDot/index.js, react/src/Communications/Toast/Toast.js, react/src/Communications/Toast/index.js, react/src/Communications/Token/Token.js, react/src/Communications/Token/index.js, react/src/Communications/ToolTip/ToolTip.js, react/src/Communications/ToolTip/index.js
Current Problem
None
After Implementation
Communication empty components added
Steps to Reproduce this issue
None
=> Communications component structure

.vscode/settings.json
- Prettier setting is not good
- Now its better
=> tech: add vscode settings

react/src/CallsToAction/ButtonGroup/ButtonGroup.js, react/src/Icon.js
=> feat(cta/button-group): add base component with three examples

react-examples/stories/ButtonGroup.stories.js, react-examples/stories/FloatingButton.stories.js, react/src/CallsToAction/FloatingButton/FloatingButton.js
- There is no option to float the button
- This button can float multiple places
=> feat(cta/floating-button): add base component along with story book docs and Button Group docs

react/src/Containers/Card/Card.js, react/src/Containers/Card/index.js, react/src/Containers/Divider/Divider.js, react/src/Containers/Divider/index.js, react/src/Containers/Flexbox/Flexbox.js, react/src/Containers/Flexbox/index.js, react/src/Containers/Modal/Modal.js, react/src/Containers/Modal/index.js, react/src/Containers/Overflow/Overflow.js, react/src/Containers/Overflow/index.js, react/src/Containers/Page/Page.js, react/src/Containers/Page/index.js, react/src/Containers/PageHeader/PageHeader.js, react/src/Containers/PageHeader/index.js, react/src/Containers/Panel/Panel.js, react/src/Containers/Panel/index.js, react/src/Containers/Popover/Popover.js, react/src/Containers/Popover/index.js, react/src/Containers/Scroll/Scroll.js, react/src/Containers/Scroll/index.js, react/src/Containers/Section/Section.js, react/src/Containers/Section/index.js, react/src/Containers/SplitPane/SplitPane.js, react/src/Containers/SplitPane/index.js
None
Added Empty Container  components
None
=>  Added Empty Container  component

react-examples/stories/Link.stories.js, react/src/Badges.js, react/src/CallsToAction/Link/Link.js
Badge was not proper
1.Added Link story examples
2.Changed to single badge component
None
=> Added Link storybook component and changed badge component

react-examples/stories/Communications/Tooltip.stories.js, react/src/Communications/ToolTip/ToolTip.js, react/src/index.js
=> feat(communication/tool-tip): add Tooltip Component

react-examples/stories/List/CollapsibleList.stories.js, react/src/List/CollapsibleList/CollapsibleList.js
=> feat(collapse-list): add 3 basic example

react-examples/stories/Containers/Popover.stories.js, react-examples/stories/Input/DatePicker.stories.js, react-examples/stories/Input/TimePicker.stories.js, react/package-lock.json, react/package.json, react/src/Containers/Popover/Popover.js, react/src/Inputs/DateOrTimeInput/DateOrTimeInput.js, react/src/Inputs/DateOrTimeInput/DatePicker.js, react/src/Inputs/DateOrTimeInput/TimePicker.js, react/src/Inputs/DateOrTimeInput/index.js, react/src/index.js
There is no option to choose date, time and popover
=> feat(input): add date and time selector

react-examples/stories/Alert.stories.js, react-examples/stories/Comments.stories.js, react-examples/stories/Containers/BoxItem.stories.js, react-examples/stories/CopyButton.stories.js, react-examples/stories/CopyLink.stories.js, react-examples/stories/Input/CodeEditor.stories.js, react-examples/stories/Input/DatePicker.stories.js, react-examples/stories/Input/TimePicker.stories.js, react/package-lock.json, react/package.json, react/src/Inputs/CodeEditor/CodeEditor.js
There is no language options
none
=> feat(input/code-editor): add base code

react-examples/stories/Communications/Toast.stories.js, react/src/Communications/Toast/Toast.js, react/src/index.js
=> feat(communications): add toast component

react-examples/stories/Checkbox.stories.js, react/src/Inputs/Checkbox/Checkbox.js, react/src/Inputs/Checkbox/index.js, react/src/_deprecated/Checkbox.js, react/src/index.js
- There is  no option for disable case, move input to right side.
- Refer screenshot
=> feat(input/checkbox): add base changes

react-examples/stories/Inputs/Checkbox.stories.js, react-examples/stories/Inputs/CodeEditor.stories.js, react-examples/stories/Inputs/DatePicker.stories.js, react-examples/stories/Inputs/Radio.stories.js, react-examples/stories/Inputs/TimePicker.stories.js, react/src/Inputs/Radio/Radio.js, react/src/Inputs/Radio/index.js
- There is no radio button 
- Refer screenshot
=> feat(input/radio): add base changes

react-examples/stories/Inputs/InputSingleLine.stories.js, react/src/Icon.js, react/src/Inputs/InputSingleLine/InputSingleLine.js, react/src/Inputs/InputSingleLine/index.js, react/src/Visualization/DataTable/DataTable.js, react/src/Visualization/DataTable/index.js, react/src/Visualization/SimpleTable/SimpleTable.js, react/src/Visualization/SimpleTable/index.js, react/src/Visualization/Table/Table.js, react/src/Visualization/Table/index.js, react/src/index.js
There is no below option
1. Support for Left Icon for example like User Icon
2. Option to clear the value using right side clear icon
3. Support for Right Icon for example like Date Picker on click of popover
4. Disabled use case
5. State of Success, Error, Warning, Info
=> feat(inputs/InputSingleLine): add base changes for input

react-examples/stories/Communications/Notice.stories.js, react/src/Communications/Notice/Notice.js, react/src/index.js
=> feat(communications): add notice component

react-examples/stories/Inputs/InputSingleLine.stories.js, react/src/Icon.js, react/src/Inputs/InputSingleLine/InputSingleLine.js
1. Update label, left icon spacing
=> feat(inputs/single-input): update label, left icon spacing

react-examples/stories/Communications/StatusDot.stories.js, react/src/Communications/StatusDot/StatusDot.js, react/src/Communications/StatusDot/index.js
=> feat(communications): add status dot component

react-examples/stories/CallsToAction/Button.stories.js, react-examples/stories/Inputs/CheckboxDropdown.stories.js, react-examples/stories/Inputs/RadioDropdown.stories.js, react/src/Inputs/CheckBoxDropdown/CheckBoxDropdown.js, react/src/Inputs/CheckBoxDropdown/index.js
There is no dropdown for multiple selection
1. Able to consume the existing TwixtRadio Component
2. Able to select multiple options
3. Label will be updated as configurable "count" item selected
4. Added option to filter the options
-
=> feat(input/radioDropdown): add base code with below features

react/src/index.js
Twixt not working since index is not proper
Fixed the path in index
None
=> fix(index):Deprecated Tooltip and Popover
